# Install NumPy library

In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


# NumPy Array Operation

# 1. Import Library

In [2]:
import numpy as np

## 2. NumPy version Check

In [3]:
np.version.version

'1.24.4'

# 3.1 Creating 1D array

# 1.Syntax: numpy.array ([Values])


# 2.Values: Element in  the array

In [4]:
first_array = np.array([1,2,3,4,5])

## 3.2 Printing 1D array

In [5]:
print(first_array)

[1 2 3 4 5]


## 4.1 Creating 2D array

# 1.Syntax: numpy.array ([Values])


# 2.Values: Element in  the array

In [6]:
second_array = np.array([(4,5,6),(7,8,9)])

In [7]:
print(second_array)

[[4 5 6]
 [7 8 9]]


# 5.1 Creating 3D array

# 1.Syntax: numpy.array ([Values])


# 2.Values: Element in  the array

In [8]:
third_array = np.array([[(10,11,12),(13,14,15)],[(16,17,18),(19,20,21)]])

In [9]:
print(third_array)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [19 20 21]]]


In [10]:
zero_array = np.zeros((4,4))

In [11]:
print(zero_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 7.Array of Ones

In [12]:
one_array = np.ones((10,10))
print(one_array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 8. Linspace

In [13]:
spaced_num = np.linspace(0,100,500)

In [14]:
print(spaced_num)

[  0.           0.2004008    0.4008016    0.6012024    0.80160321
   1.00200401   1.20240481   1.40280561   1.60320641   1.80360721
   2.00400802   2.20440882   2.40480962   2.60521042   2.80561122
   3.00601202   3.20641283   3.40681363   3.60721443   3.80761523
   4.00801603   4.20841683   4.40881764   4.60921844   4.80961924
   5.01002004   5.21042084   5.41082164   5.61122244   5.81162325
   6.01202405   6.21242485   6.41282565   6.61322645   6.81362725
   7.01402806   7.21442886   7.41482966   7.61523046   7.81563126
   8.01603206   8.21643287   8.41683367   8.61723447   8.81763527
   9.01803607   9.21843687   9.41883768   9.61923848   9.81963928
  10.02004008  10.22044088  10.42084168  10.62124248  10.82164329
  11.02204409  11.22244489  11.42284569  11.62324649  11.82364729
  12.0240481   12.2244489   12.4248497   12.6252505   12.8256513
  13.0260521   13.22645291  13.42685371  13.62725451  13.82765531
  14.02805611  14.22845691  14.42885772  14.62925852  14.82965932
  15.030060

In [15]:
my_array = np.array([1,2,3])
print(my_array)

[1 2 3]


In [16]:
arr_ones =np.ones((2,2))
print(arr_ones)

[[1. 1.]
 [1. 1.]]


In [17]:
my_matrix = np.array([(10,11,12),(13,14,15)])
print(my_matrix)

[[10 11 12]
 [13 14 15]]


In [18]:
matrix_transpose = np.transpose(my_matrix)
print(matrix_transpose)

[[10 13]
 [11 14]
 [12 15]]


In [19]:
matrix_transpose.ravel()

array([10, 13, 11, 14, 12, 15])

# Array reshape

In [20]:
my_array.reshape(3,1)

array([[1],
       [2],
       [3]])

In [21]:
arr_ones.reshape(4,1)

array([[1.],
       [1.],
       [1.],
       [1.]])

In [23]:
matrix_transpose.reshape(2,3)

array([[10, 13, 11],
       [14, 12, 15]])

# Array resize

In [26]:
arr_ones.resize(4,1)
arr_ones

array([[1.],
       [1.],
       [1.],
       [1.]])

In [27]:
np.random.random((3,3))

array([[0.62752114, 0.14531398, 0.22860817],
       [0.86126572, 0.46121994, 0.80679741],
       [0.69810602, 0.45356194, 0.75928697]])